### ISSUE TITLE
Error when uploading

### ISSUE THREAD

**Issue by kframnes1** [adamdavi3s/QlikviewSankeyImproved#1]
Hi. Im getting the error msg: "The zip file did not contain any valid extensions". 

Can you help? 

Also is it possible to add sorting option? 
I'm using the sankey graph for an origin-destination model so it would be nice to sort the station in the direction they are driving :)

**Comment by adamdavi3s** [comment]
Hmmm what version of desktop do you have?
It seems to run fine on mine (12 SR4) and it should be OK on 11+

I'll check out the sorting, can you scope it a bit more? i can't quite picture it in my mind

**Comment by kframnes1** [comment]
Hi. Thanks for replying so fast :) 
I am not working on the desktop but the hub? 
The latest version 3.1

Let me try to explain: 
So i have a model that estimates where people who enters a train gets og. So if 20 people get on at station #2, how many exits from station #3 #4 etc..... I am using the sankey map and displaying origin stations on the left side og the destination stations on the right side. Right now I can not sort the stations. I have an attribute that sets an order of the stations as they drive. The graph would be more powerful when the stations are sorted after the order they drive :)

**Comment by adamdavi3s** [comment]
No worries!

I am afraid this is a VIEW not a SENSE extension though!

That sorting does make sense, you can manually drag them around with most Sankey extensions but I agree it would be useful to be able to have the system do it for you

**Comment by kframnes1** [comment]
Oh my bad :) Sorry 
Thank you for replying fast :)

**Comment by adamdavi3s** [comment]
That is OK, at some point I will convert it to sense and I'll update this to let you know )
